### ISSUE TITLE
add_prefix_mapping disappeared in the transition from 1.0.0 to 1.0.1

### ISSUE THREAD

**Issue by cmungall** [ontology-tools/py-horned-owl#34]
This example here:

https://github.com/ontology-tools/py-horned-owl/blob/main/docs/source/quickstart.rst#L26

shows a method `add_prefix_mapping`

This worked in 1.0.0, and I have been using it in my code

This disappeared in 1.0.1

Example:

```python
>>> import pyhornedowl
>>> ontology = pyhornedowl.open_ontology("./tests/test_frameworks/hornedowl/input/ro.ofn")
>>> axioms = ontology.get_axioms()
>>> ontology.add_prefix_mapping(":", "https://example.com/test#")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'builtins.PyIndexedOntology' object has no attribute 'add_prefix_mapping'. Did you mean: 'prefix_mapping'?
```

**Comment by cmungall** [comment]
Aside: the link to the changelog in https://github.com/ontology-tools/py-horned-owl/releases/tag/v1.0.1 goes to the wrong version...

**Comment by cmungall** [comment]
It looks like there is now a separate `PrefixMapping` object. This makes sense,  but it seems to work differently

This used to work:

```python
o = PyIndexedOntology()
o.add_prefix_mapping("", "http://example.org/")
C = o.clazz("C")
```

This is my attempt to migrate to 1.0.1:

```python
o = PyIndexedOntology()
o.prefix_mapping.add_prefix("", "http://example.org/")
C = o.clazz("C")
```

`ValueError: Invalid curie: MissingDefault`

so in addition to the method disappearing, there seems to be a different way to add base prefixes?
